name: ledger_mobile
description: Mobile app for Ledger Dashboard (Flutter)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^14.2.3
  intl: ^0.19.0
  fl_chart: ^0.69.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
